{% set name = "foundry-dev-tools" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/foundry_dev_tools-{{ version }}.tar.gz
  sha256: 771441a86652c5f732fa1f76263ac14450d142322cc19c10b83f8927c5c1b75b

build:
  noarch: python
  entry_points:
    - fdt = foundry_dev_tools.cli.main:cli
    - git-credential-foundry = foundry_dev_tools.cli.git_credential_foundry:_helper
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pdm-backend
    - pip
  run:
    - python >=3.10
    - requests
    - palantir-oauth-client
    - platformdirs
    - tomli
    - typing_extensions
    - click
    - inquirer
    - websockets
    - rich
    - packaging
    - tomli-w

test:
  imports:
    - foundry_dev_tools
  commands:
    - pip check
    - fdt --help
  requires:
    - pip

about:
  home: https://github.com/emdgroup/foundry-dev-tools
  summary: Seamlessly run your Palantir Foundry Repository transforms code on your local machine.
  dev_url: https://github.com/emdgroup/foundry-dev-tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicornk
    - jonas-w
